version: "3"

services:

#  cache:
#    image: octopot/tablo:cache
#    build:
#      context: ../cache
#    env_file:
#      - ../cache/.env
#
#  monitoring:
#    image: octopot/tablo:monitoring
#    build:
#      context: ../monitoring
#    env_file:
#      - ../monitoring/.env

  server:
    image: octopot/tablo:server
    build:
      context: ../server
    depends_on:
      - service
    env_file:
      - ../server/.env

  service:
    image: octopot/tablo:latest
    build:
      context: ../../../.
      dockerfile: env/docker/service/Dockerfile
    env_file:
      - ../service/.env

  storage:
    image: octopot/tablo:storage
    build:
      context: ../storage
    env_file:
      - ../storage/.env
