version: "3"

services:

  server:
    ports:
      - 80:80
      - 443:443
    volumes:
      - certificates:/etc/nginx/ssl
      - letsencrypt:/etc/letsencrypt

  service:
    ports:
      - 8080:8080

  storage:
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:

  certificates: { driver: local }
  letsencrypt:  { driver: local }

  pgdata: { driver: local }
