version: "3"

services:

  service:
    image: octopot/tablo:latest
    build:
      context: ../../../.
      dockerfile: env/docker/service/Dockerfile
    env_file:
      - ../service/.env

  storage:
    image: octopot/tablo:storage
    build:
      context: ../storage/context
      dockerfile: ../Dockerfile
    env_file:
      - ../storage/.env
