POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/CreateCard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.card.CreateCard.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/GetCard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.card.GetCard.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/UpdateCard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.card.UpdateCard.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/DeleteCard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.card.DeleteCard.json

###
