POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/CreateCard
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "column_id": {
    "urn": "78B30F56-4EBD-43A3-950D-0F830FA12026"
  },
  "title": "up stub http server",
  "emoji": "📦",
  "desc": "Use stub data as responses of API.",
  "url": "https://github.com/octopot/tablo/issues/1",
  "labels": ["type:task"]
}

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/GetCard
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "urn": "7F35888A-2B4B-4BD6-83AB-B5E0E5B65AFA"
}

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/UpdateCard
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": {
    "urn": "7F35888A-2B4B-4BD6-83AB-B5E0E5B65AFA"
  },
  "title": "up stub http server",
  "emoji": "📦",
  "desc": "Describe stub data as responses of API.",
  "url": "https://github.com/octopot/tablo/issues/1",
  "labels": ["type:task"]
}

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/DeleteCard
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "urn": "7F35888A-2B4B-4BD6-83AB-B5E0E5B65AFA"
}

###
