POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/CreateColumn
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.column.CreateColumn.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/GetColumn
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.column.GetColumn.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/UpdateColumn
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.column.UpdateColumn.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/DeleteColumn
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.column.DeleteColumn.json

###
