- name: Pull the service image
  docker_image:
    name:   octopot/tablo
    tag:    latest
    source: pull

- name: Pull the storage image
  docker_image:
    name:   octopot/tablo
    tag:    storage
    source: pull

- name: Register GitHub host
  known_hosts:
    name: github.com
    key:  github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    hash_host: yes
    state:     present

- name: Pull the project
  git:
    repo:   git@github.com:octopot/tablo.git
    dest:   /opt/tablo
    update: yes
