- name: Install required packages for Python
  apt:
    name:
      - python3-pip
      - python3-setuptools
    state: present

- name: Install Docker Compose
  pip:
    name:
      - docker=={{ docker_version }}
      - docker-compose=={{ docker_compose_version }}
    state: present
