POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/CreateBoard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.board.CreateBoard.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/GetBoard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.board.GetBoard.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/GetBoards
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.board.GetBoards.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/UpdateBoard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.board.UpdateBoard.json

###

POST {{host}}/twirp/octolab.api.tablo.v1.TabloService/DeleteBoard
Authorization: Bearer {{token}}
Content-Type: application/json

< payload/rpc.v1.board.DeleteBoard.json

###
