// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

// +build tools

package tools

// tool dependencies
import (
	_ "github.com/go-swagger/go-swagger/cmd/swagger"
	_ "github.com/golang/mock/mockgen"
	_ "github.com/golang/protobuf/protoc-gen-go"
	_ "github.com/golangci/golangci-lint/cmd/golangci-lint"
	_ "github.com/goreleaser/godownloader"
	_ "github.com/goreleaser/goreleaser"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"
	_ "github.com/twitchtv/twirp/protoc-gen-twirp"
	_ "golang.org/x/tools/cmd/goimports"
)
